// Autogenerated with StateSmith 0.17.2+a7141c241054b3177bab267557ecb45a8dcedd67.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "SMSodaStreamPure.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
// #include "your_header_here.h"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(SMSodaStreamPure* sm, SMSodaStreamPure_StateId desired_state);

static void ROOT_enter(SMSodaStreamPure* sm);

static void SATE_HWWATCHDOG_enter(SMSodaStreamPure* sm);

static void SATE_HWWATCHDOG_exit(SMSodaStreamPure* sm);

static void SATE_SAFETYFAIL_enter(SMSodaStreamPure* sm);

static void SATE_SAFETYFAIL_exit(SMSodaStreamPure* sm);

static void SATE_TILTED_enter(SMSodaStreamPure* sm);

static void SATE_TILTED_exit(SMSodaStreamPure* sm);

static void SATE_TILTED_event_hwwatchdog(SMSodaStreamPure* sm);

static void SATE_TILTED_event_nottilted(SMSodaStreamPure* sm);

static void SATE_TILTED_event_safetyfail(SMSodaStreamPure* sm);

static void STATE_NORMALOPERATION_enter(SMSodaStreamPure* sm);

static void STATE_NORMALOPERATION_exit(SMSodaStreamPure* sm);

static void STATE_NORMALOPERATION_event_hwwatchdog(SMSodaStreamPure* sm);

static void STATE_NORMALOPERATION_event_safetyfail(SMSodaStreamPure* sm);

static void STATE_NORMALOPERATION_event_tiltdetected(SMSodaStreamPure* sm);

static void SATE_CARBONATING_enter(SMSodaStreamPure* sm);

static void SATE_CARBONATING_exit(SMSodaStreamPure* sm);

static void SATE_CARBONATING_event_anykeypress(SMSodaStreamPure* sm);

static void SATE_CARBONATING_event_carbonationdone(SMSodaStreamPure* sm);

static void SATE_INITCARBONATINGONLY_enter(SMSodaStreamPure* sm);

static void SATE_INITCARBONATINGONLY_exit(SMSodaStreamPure* sm);

static void SATE_INITCARBONATINGONLY_do(SMSodaStreamPure* sm);

static void STATE_EXITFILTERINGONLY_enter(SMSodaStreamPure* sm);

static void STATE_EXITFILTERINGONLY_exit(SMSodaStreamPure* sm);

static void STATE_EXITFILTERINGONLY_do(SMSodaStreamPure* sm);

static void STATE_FILTERING_enter(SMSodaStreamPure* sm);

static void STATE_FILTERING_exit(SMSodaStreamPure* sm);

static void STATE_FILTERING_event_bottlefullsensor(SMSodaStreamPure* sm);

static void STATE_FILTERING_event_carbonationlevelpressed(SMSodaStreamPure* sm);

static void STATE_FILTERING_event_waterfilterpressed(SMSodaStreamPure* sm);

static void STATE_FILTERING_event_waterpumpingtimeout(SMSodaStreamPure* sm);

static void STATE_FILTERINGCARBONATIONAWAIT_enter(SMSodaStreamPure* sm);

static void STATE_FILTERINGCARBONATIONAWAIT_exit(SMSodaStreamPure* sm);

static void STATE_FILTERINGCARBONATIONAWAIT_event_anykeypress(SMSodaStreamPure* sm);

static void STATE_FILTERINGCARBONATIONAWAIT_event_bottlefullsensor(SMSodaStreamPure* sm);

static void STATE_FILTERINGCARBONATIONAWAIT_event_waterpumpingtimertimeout(SMSodaStreamPure* sm);

static void STATE_POWERON_enter(SMSodaStreamPure* sm);

static void STATE_POWERON_exit(SMSodaStreamPure* sm);

static void STATE_POWERON_event_carbonationlevelpressed(SMSodaStreamPure* sm);

static void STATE_POWERON_event_longpresswaterfilter(SMSodaStreamPure* sm);

static void STATE_POWERON_event_shortpresswaterfilter(SMSodaStreamPure* sm);

static void State_PowerOn_ChoicePoint__transition(SMSodaStreamPure* sm);

static void STATE_POWERONINIT_enter(SMSodaStreamPure* sm);

static void STATE_POWERONINIT_exit(SMSodaStreamPure* sm);

static void STATE_POWERONINIT_do(SMSodaStreamPure* sm);

static void STATE_READY_enter(SMSodaStreamPure* sm);

static void STATE_READY_exit(SMSodaStreamPure* sm);

static void STATE_READY_event_readytimout(SMSodaStreamPure* sm);

static void STATE_READYRINSEREQUIRED_enter(SMSodaStreamPure* sm);

static void STATE_READYRINSEREQUIRED_exit(SMSodaStreamPure* sm);

static void STATE_READYRINSEREQUIRED_event_readytimout(SMSodaStreamPure* sm);

static void STATE_STANDBY_enter(SMSodaStreamPure* sm);

static void STATE_STANDBY_exit(SMSodaStreamPure* sm);

static void STATE_RINSING_enter(SMSodaStreamPure* sm);

static void STATE_RINSING_exit(SMSodaStreamPure* sm);

static void STATE_RINSING_event_anykeypress(SMSodaStreamPure* sm);

static void STATE_RINSING_event_bottlefullsensor(SMSodaStreamPure* sm);

static void STATE_RINSING_event_waterpumpingtimeout(SMSodaStreamPure* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void SMSodaStreamPure_ctor(SMSodaStreamPure* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void SMSodaStreamPure_start(SMSodaStreamPure* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(State_NormalOperation)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `State_NormalOperation`.
            STATE_NORMALOPERATION_enter(sm);
            
            // State_NormalOperation.<InitialState> behavior
            // uml: TransitionTo(State_PowerOn)
            {
                // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `State_PowerOn`.
                STATE_POWERON_enter(sm);
                
                // State_PowerOn.<InitialState> behavior
                // uml: TransitionTo(State_PowerOnInit)
                {
                    // Step 1: Exit states until we reach `State_PowerOn` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                    
                    // Step 2: Transition action: ``.
                    
                    // Step 3: Enter/move towards transition target `State_PowerOnInit`.
                    STATE_POWERONINIT_enter(sm);
                    
                    // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                    return;
                } // end of behavior for State_PowerOn.<InitialState>
            } // end of behavior for State_NormalOperation.<InitialState>
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void SMSodaStreamPure_dispatch_event(SMSodaStreamPure* sm, SMSodaStreamPure_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: SMSodaStreamPure
        case SMSodaStreamPure_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: Sate_HWWatchdog
        case SMSodaStreamPure_StateId_SATE_HWWATCHDOG:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: Sate_SafetyFail
        case SMSodaStreamPure_StateId_SATE_SAFETYFAIL:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: Sate_Tilted
        case SMSodaStreamPure_StateId_SATE_TILTED:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: SATE_TILTED_event_hwwatchdog(sm); break;
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: SATE_TILTED_event_safetyfail(sm); break;
                case SMSodaStreamPure_EventId_EVENT_NOTTILTED: SATE_TILTED_event_nottilted(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_NormalOperation
        case SMSodaStreamPure_StateId_STATE_NORMALOPERATION:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break;
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Sate_Carbonating
        case SMSodaStreamPure_StateId_SATE_CARBONATING:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_CARBONATIONDONE: SATE_CARBONATING_event_carbonationdone(sm); break;
                case SMSodaStreamPure_EventId_EVENT_ANYKEYPRESS: SATE_CARBONATING_event_anykeypress(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Sate_InitCarbonatingOnly
        case SMSodaStreamPure_StateId_SATE_INITCARBONATINGONLY:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_DO: SATE_INITCARBONATINGONLY_do(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_ExitFilteringOnly
        case SMSodaStreamPure_StateId_STATE_EXITFILTERINGONLY:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_DO: STATE_EXITFILTERINGONLY_do(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_Filtering
        case SMSodaStreamPure_StateId_STATE_FILTERING:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED: STATE_FILTERING_event_carbonationlevelpressed(sm); break;
                case SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMEOUT: STATE_FILTERING_event_waterpumpingtimeout(sm); break;
                case SMSodaStreamPure_EventId_EVENT_WATERFILTERPRESSED: STATE_FILTERING_event_waterfilterpressed(sm); break;
                case SMSodaStreamPure_EventId_EVENT_BOTTLEFULLSENSOR: STATE_FILTERING_event_bottlefullsensor(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_FilteringCarbonationAwait
        case SMSodaStreamPure_StateId_STATE_FILTERINGCARBONATIONAWAIT:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_ANYKEYPRESS: STATE_FILTERINGCARBONATIONAWAIT_event_anykeypress(sm); break;
                case SMSodaStreamPure_EventId_EVENT_BOTTLEFULLSENSOR: STATE_FILTERINGCARBONATIONAWAIT_event_bottlefullsensor(sm); break;
                case SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMERTIMEOUT: STATE_FILTERINGCARBONATIONAWAIT_event_waterpumpingtimertimeout(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_PowerOn
        case SMSodaStreamPure_StateId_STATE_POWERON:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_LONGPRESSWATERFILTER: STATE_POWERON_event_longpresswaterfilter(sm); break;
                case SMSodaStreamPure_EventId_EVENT_SHORTPRESSWATERFILTER: STATE_POWERON_event_shortpresswaterfilter(sm); break;
                case SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED: STATE_POWERON_event_carbonationlevelpressed(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_PowerOnInit
        case SMSodaStreamPure_StateId_STATE_POWERONINIT:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_DO: STATE_POWERONINIT_do(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_LONGPRESSWATERFILTER: STATE_POWERON_event_longpresswaterfilter(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SHORTPRESSWATERFILTER: STATE_POWERON_event_shortpresswaterfilter(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED: STATE_POWERON_event_carbonationlevelpressed(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_Ready
        case SMSodaStreamPure_StateId_STATE_READY:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_READYTIMOUT: STATE_READY_event_readytimout(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_LONGPRESSWATERFILTER: STATE_POWERON_event_longpresswaterfilter(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SHORTPRESSWATERFILTER: STATE_POWERON_event_shortpresswaterfilter(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED: STATE_POWERON_event_carbonationlevelpressed(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_ReadyRinseRequired
        case SMSodaStreamPure_StateId_STATE_READYRINSEREQUIRED:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_READYTIMOUT: STATE_READYRINSEREQUIRED_event_readytimout(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_LONGPRESSWATERFILTER: STATE_POWERON_event_longpresswaterfilter(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SHORTPRESSWATERFILTER: STATE_POWERON_event_shortpresswaterfilter(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED: STATE_POWERON_event_carbonationlevelpressed(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_StandBy
        case SMSodaStreamPure_StateId_STATE_STANDBY:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_LONGPRESSWATERFILTER: STATE_POWERON_event_longpresswaterfilter(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SHORTPRESSWATERFILTER: STATE_POWERON_event_shortpresswaterfilter(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED: STATE_POWERON_event_carbonationlevelpressed(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: State_Rinsing
        case SMSodaStreamPure_StateId_STATE_RINSING:
            switch (event_id)
            {
                case SMSodaStreamPure_EventId_EVENT_ANYKEYPRESS: STATE_RINSING_event_anykeypress(sm); break;
                case SMSodaStreamPure_EventId_EVENT_BOTTLEFULLSENSOR: STATE_RINSING_event_bottlefullsensor(sm); break;
                case SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMEOUT: STATE_RINSING_event_waterpumpingtimeout(sm); break;
                case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: STATE_NORMALOPERATION_event_hwwatchdog(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: STATE_NORMALOPERATION_event_safetyfail(sm); break; // First ancestor handler for this event
                case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: STATE_NORMALOPERATION_event_tiltdetected(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(SMSodaStreamPure* sm, SMSodaStreamPure_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case SMSodaStreamPure_StateId_SATE_HWWATCHDOG: SATE_HWWATCHDOG_exit(sm); break;
            
            case SMSodaStreamPure_StateId_SATE_SAFETYFAIL: SATE_SAFETYFAIL_exit(sm); break;
            
            case SMSodaStreamPure_StateId_SATE_TILTED: SATE_TILTED_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_NORMALOPERATION: STATE_NORMALOPERATION_exit(sm); break;
            
            case SMSodaStreamPure_StateId_SATE_CARBONATING: SATE_CARBONATING_exit(sm); break;
            
            case SMSodaStreamPure_StateId_SATE_INITCARBONATINGONLY: SATE_INITCARBONATINGONLY_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_EXITFILTERINGONLY: STATE_EXITFILTERINGONLY_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_FILTERING: STATE_FILTERING_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_FILTERINGCARBONATIONAWAIT: STATE_FILTERINGCARBONATIONAWAIT_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_POWERON: STATE_POWERON_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_POWERONINIT: STATE_POWERONINIT_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_READY: STATE_READY_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_READYRINSEREQUIRED: STATE_READYRINSEREQUIRED_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_STANDBY: STATE_STANDBY_exit(sm); break;
            
            case SMSodaStreamPure_StateId_STATE_RINSING: STATE_RINSING_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SATE_HWWATCHDOG
////////////////////////////////////////////////////////////////////////////////

static void SATE_HWWATCHDOG_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_SATE_HWWATCHDOG;
    
    // Sate_HWWatchdog behavior
    // uml: enter / { StopWaterPump(); }
    {
        // Step 1: execute action `StopWaterPump();`
        StopWaterPump();
    } // end of behavior for Sate_HWWatchdog
    
    // Sate_HWWatchdog behavior
    // uml: enter / { StopUVLed(); }
    {
        // Step 1: execute action `StopUVLed();`
        StopUVLed();
    } // end of behavior for Sate_HWWatchdog
    
    // Sate_HWWatchdog behavior
    // uml: enter / { StopCarbonation(); }
    {
        // Step 1: execute action `StopCarbonation();`
        StopCarbonation();
    } // end of behavior for Sate_HWWatchdog
    
    // Sate_HWWatchdog behavior
    // uml: enter / { StartMalfunctionLedsSequence(); }
    {
        // Step 1: execute action `StartMalfunctionLedsSequence();`
        StartMalfunctionLedsSequence();
    } // end of behavior for Sate_HWWatchdog
    
    // Sate_HWWatchdog behavior
    // uml: enter / { FadeOutAmbiantLight(); }
    {
        // Step 1: execute action `FadeOutAmbiantLight();`
        FadeOutAmbiantLight();
    } // end of behavior for Sate_HWWatchdog
}

static void SATE_HWWATCHDOG_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SATE_SAFETYFAIL
////////////////////////////////////////////////////////////////////////////////

static void SATE_SAFETYFAIL_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_SATE_SAFETYFAIL;
    
    // Sate_SafetyFail behavior
    // uml: enter / { StopWaterPump(); }
    {
        // Step 1: execute action `StopWaterPump();`
        StopWaterPump();
    } // end of behavior for Sate_SafetyFail
    
    // Sate_SafetyFail behavior
    // uml: enter / { StopUVLed(); }
    {
        // Step 1: execute action `StopUVLed();`
        StopUVLed();
    } // end of behavior for Sate_SafetyFail
    
    // Sate_SafetyFail behavior
    // uml: enter / { StopCarbonation(); }
    {
        // Step 1: execute action `StopCarbonation();`
        StopCarbonation();
    } // end of behavior for Sate_SafetyFail
    
    // Sate_SafetyFail behavior
    // uml: enter / { StartMalfunctionLedsSequence(); }
    {
        // Step 1: execute action `StartMalfunctionLedsSequence();`
        StartMalfunctionLedsSequence();
    } // end of behavior for Sate_SafetyFail
    
    // Sate_SafetyFail behavior
    // uml: enter / { FadeOutAmbiantLight(); }
    {
        // Step 1: execute action `FadeOutAmbiantLight();`
        FadeOutAmbiantLight();
    } // end of behavior for Sate_SafetyFail
}

static void SATE_SAFETYFAIL_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SATE_TILTED
////////////////////////////////////////////////////////////////////////////////

static void SATE_TILTED_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_SATE_TILTED;
    
    // Sate_Tilted behavior
    // uml: enter / { StopWaterPump(); }
    {
        // Step 1: execute action `StopWaterPump();`
        StopWaterPump();
    } // end of behavior for Sate_Tilted
    
    // Sate_Tilted behavior
    // uml: enter / { StopUVLed(); }
    {
        // Step 1: execute action `StopUVLed();`
        StopUVLed();
    } // end of behavior for Sate_Tilted
    
    // Sate_Tilted behavior
    // uml: enter / { StopCarbonation(); }
    {
        // Step 1: execute action `StopCarbonation();`
        StopCarbonation();
    } // end of behavior for Sate_Tilted
    
    // Sate_Tilted behavior
    // uml: enter / { StartMalfunctionLedsSequence(); }
    {
        // Step 1: execute action `StartMalfunctionLedsSequence();`
        StartMalfunctionLedsSequence();
    } // end of behavior for Sate_Tilted
    
    // Sate_Tilted behavior
    // uml: enter / { FadeOutAmbiantLight(); }
    {
        // Step 1: execute action `FadeOutAmbiantLight();`
        FadeOutAmbiantLight();
    } // end of behavior for Sate_Tilted
}

static void SATE_TILTED_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_ROOT;
}

static void SATE_TILTED_event_hwwatchdog(SMSodaStreamPure* sm)
{
    // Sate_Tilted behavior
    // uml: Event_HWWatchdog TransitionTo(Sate_HWWatchdog)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        SATE_TILTED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Sate_HWWatchdog`.
        SATE_HWWATCHDOG_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Sate_Tilted
    
    // No ancestor handles this event.
}

static void SATE_TILTED_event_nottilted(SMSodaStreamPure* sm)
{
    // Sate_Tilted behavior
    // uml: Event_NotTilted TransitionTo(State_PowerOn.<ChoicePoint>())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        SATE_TILTED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_PowerOn.<ChoicePoint>()`.
        STATE_NORMALOPERATION_enter(sm);
        STATE_POWERON_enter(sm);
        // State_PowerOn.<ChoicePoint>() is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        State_PowerOn_ChoicePoint__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Sate_Tilted
    
    // No ancestor handles this event.
}

static void SATE_TILTED_event_safetyfail(SMSodaStreamPure* sm)
{
    // Sate_Tilted behavior
    // uml: Event_SafetyFail TransitionTo(Sate_SafetyFail)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        SATE_TILTED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Sate_SafetyFail`.
        SATE_SAFETYFAIL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Sate_Tilted
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_NORMALOPERATION
////////////////////////////////////////////////////////////////////////////////

static void STATE_NORMALOPERATION_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_NORMALOPERATION;
}

static void STATE_NORMALOPERATION_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_ROOT;
}

static void STATE_NORMALOPERATION_event_hwwatchdog(SMSodaStreamPure* sm)
{
    // State_NormalOperation behavior
    // uml: Event_HWWatchdog TransitionTo(Sate_HWWatchdog)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SMSodaStreamPure_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Sate_HWWatchdog`.
        SATE_HWWATCHDOG_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_NormalOperation
    
    // No ancestor handles this event.
}

static void STATE_NORMALOPERATION_event_safetyfail(SMSodaStreamPure* sm)
{
    // State_NormalOperation behavior
    // uml: Event_SafetyFail TransitionTo(Sate_SafetyFail)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SMSodaStreamPure_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Sate_SafetyFail`.
        SATE_SAFETYFAIL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_NormalOperation
    
    // No ancestor handles this event.
}

static void STATE_NORMALOPERATION_event_tiltdetected(SMSodaStreamPure* sm)
{
    // State_NormalOperation behavior
    // uml: Event_TiltDetected TransitionTo(Sate_Tilted)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SMSodaStreamPure_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Sate_Tilted`.
        SATE_TILTED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_NormalOperation
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SATE_CARBONATING
////////////////////////////////////////////////////////////////////////////////

static void SATE_CARBONATING_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_SATE_CARBONATING;
    
    // Sate_Carbonating behavior
    // uml: enter / { StartCarbonationLedSequance(carbonationLevel); }
    {
        // Step 1: execute action `StartCarbonationLedSequance(carbonationLevel);`
        StartCarbonationLedSequance(carbonationLevel);
    } // end of behavior for Sate_Carbonating
    
    // Sate_Carbonating behavior
    // uml: enter / { StartCarbonation(carbonationLevel); }
    {
        // Step 1: execute action `StartCarbonation(carbonationLevel);`
        StartCarbonation(carbonationLevel);
    } // end of behavior for Sate_Carbonating
}

static void SATE_CARBONATING_exit(SMSodaStreamPure* sm)
{
    // Sate_Carbonating behavior
    // uml: exit / { StopCarbonation(); }
    {
        // Step 1: execute action `StopCarbonation();`
        StopCarbonation();
    } // end of behavior for Sate_Carbonating
    
    // Sate_Carbonating behavior
    // uml: exit / { FadeOutAmbiantLight(); }
    {
        // Step 1: execute action `FadeOutAmbiantLight();`
        FadeOutAmbiantLight();
    } // end of behavior for Sate_Carbonating
    
    // Sate_Carbonating behavior
    // uml: exit / { FadeInLeds(carbonationLevel); }
    {
        // Step 1: execute action `FadeInLeds(carbonationLevel);`
        FadeInLeds(carbonationLevel);
    } // end of behavior for Sate_Carbonating
    
    sm->state_id = SMSodaStreamPure_StateId_STATE_NORMALOPERATION;
}

static void SATE_CARBONATING_event_anykeypress(SMSodaStreamPure* sm)
{
    // Sate_Carbonating behavior
    // uml: Event_AnyKeyPress TransitionTo(State_Ready)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        SATE_CARBONATING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Ready`.
        STATE_POWERON_enter(sm);
        STATE_READY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Sate_Carbonating
    
    // No ancestor handles this event.
}

static void SATE_CARBONATING_event_carbonationdone(SMSodaStreamPure* sm)
{
    // Sate_Carbonating behavior
    // uml: Event_CarbonationDone TransitionTo(State_Ready)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        SATE_CARBONATING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Ready`.
        STATE_POWERON_enter(sm);
        STATE_READY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Sate_Carbonating
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SATE_INITCARBONATINGONLY
////////////////////////////////////////////////////////////////////////////////

static void SATE_INITCARBONATINGONLY_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_SATE_INITCARBONATINGONLY;
    
    // Sate_InitCarbonatingOnly behavior
    // uml: enter / { FadeInLeds(LEDS_all); }
    {
        // Step 1: execute action `FadeInLeds(LEDS_all);`
        FadeInLeds(LEDS_all);
    } // end of behavior for Sate_InitCarbonatingOnly
    
    // Sate_InitCarbonatingOnly behavior
    // uml: enter / { FadeInAmbiantLight(); }
    {
        // Step 1: execute action `FadeInAmbiantLight();`
        FadeInAmbiantLight();
    } // end of behavior for Sate_InitCarbonatingOnly
}

static void SATE_INITCARBONATINGONLY_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_NORMALOPERATION;
}

static void SATE_INITCARBONATINGONLY_do(SMSodaStreamPure* sm)
{
    // Sate_InitCarbonatingOnly behavior
    // uml: do TransitionTo(Sate_Carbonating)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        SATE_INITCARBONATINGONLY_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Sate_Carbonating`.
        SATE_CARBONATING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Sate_InitCarbonatingOnly
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_EXITFILTERINGONLY
////////////////////////////////////////////////////////////////////////////////

static void STATE_EXITFILTERINGONLY_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_EXITFILTERINGONLY;
    
    // State_ExitFilteringOnly behavior
    // uml: enter / { StopWaterPump(); }
    {
        // Step 1: execute action `StopWaterPump();`
        StopWaterPump();
    } // end of behavior for State_ExitFilteringOnly
    
    // State_ExitFilteringOnly behavior
    // uml: enter / { StopUVLed(); }
    {
        // Step 1: execute action `StopUVLed();`
        StopUVLed();
    } // end of behavior for State_ExitFilteringOnly
    
    // State_ExitFilteringOnly behavior
    // uml: enter / { FadeOutAmbiantLight(); }
    {
        // Step 1: execute action `FadeOutAmbiantLight();`
        FadeOutAmbiantLight();
    } // end of behavior for State_ExitFilteringOnly
}

static void STATE_EXITFILTERINGONLY_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_NORMALOPERATION;
}

static void STATE_EXITFILTERINGONLY_do(SMSodaStreamPure* sm)
{
    // State_ExitFilteringOnly behavior
    // uml: do TransitionTo(State_Ready)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_EXITFILTERINGONLY_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Ready`.
        STATE_POWERON_enter(sm);
        STATE_READY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_ExitFilteringOnly
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_FILTERING
////////////////////////////////////////////////////////////////////////////////

static void STATE_FILTERING_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_FILTERING;
    
    // State_Filtering behavior
    // uml: enter / { StartWaterFilterLedSequence(); }
    {
        // Step 1: execute action `StartWaterFilterLedSequence();`
        StartWaterFilterLedSequence();
    } // end of behavior for State_Filtering
    
    // State_Filtering behavior
    // uml: enter / { FadeInLeds(LEDS_all); }
    {
        // Step 1: execute action `FadeInLeds(LEDS_all);`
        FadeInLeds(LEDS_all);
    } // end of behavior for State_Filtering
    
    // State_Filtering behavior
    // uml: enter / { FadeInAmbiantLight(); }
    {
        // Step 1: execute action `FadeInAmbiantLight();`
        FadeInAmbiantLight();
    } // end of behavior for State_Filtering
    
    // State_Filtering behavior
    // uml: enter / { StartUVLEd(); }
    {
        // Step 1: execute action `StartUVLEd();`
        StartUVLEd();
    } // end of behavior for State_Filtering
    
    // State_Filtering behavior
    // uml: enter / { StartWaterPump(); }
    {
        // Step 1: execute action `StartWaterPump();`
        StartWaterPump();
    } // end of behavior for State_Filtering
    
    // State_Filtering behavior
    // uml: enter / { StartWaterPumpingTimer(); }
    {
        // Step 1: execute action `StartWaterPumpingTimer();`
        StartWaterPumpingTimer();
    } // end of behavior for State_Filtering
}

static void STATE_FILTERING_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_NORMALOPERATION;
}

static void STATE_FILTERING_event_bottlefullsensor(SMSodaStreamPure* sm)
{
    // State_Filtering behavior
    // uml: Event_BottleFullSensor TransitionTo(State_ExitFilteringOnly)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_FILTERING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_ExitFilteringOnly`.
        STATE_EXITFILTERINGONLY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_Filtering
    
    // No ancestor handles this event.
}

static void STATE_FILTERING_event_carbonationlevelpressed(SMSodaStreamPure* sm)
{
    // State_Filtering behavior
    // uml: Event_CarbonationLevelPressed TransitionTo(State_FilteringCarbonationAwait)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_FILTERING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_FilteringCarbonationAwait`.
        STATE_FILTERINGCARBONATIONAWAIT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_Filtering
    
    // No ancestor handles this event.
}

static void STATE_FILTERING_event_waterfilterpressed(SMSodaStreamPure* sm)
{
    // State_Filtering behavior
    // uml: Event_WaterFilterPressed TransitionTo(State_ExitFilteringOnly)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_FILTERING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_ExitFilteringOnly`.
        STATE_EXITFILTERINGONLY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_Filtering
    
    // No ancestor handles this event.
}

static void STATE_FILTERING_event_waterpumpingtimeout(SMSodaStreamPure* sm)
{
    // State_Filtering behavior
    // uml: Event_WaterPumpingTimeout TransitionTo(State_ExitFilteringOnly)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_FILTERING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_ExitFilteringOnly`.
        STATE_EXITFILTERINGONLY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_Filtering
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_FILTERINGCARBONATIONAWAIT
////////////////////////////////////////////////////////////////////////////////

static void STATE_FILTERINGCARBONATIONAWAIT_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_FILTERINGCARBONATIONAWAIT;
    
    // State_FilteringCarbonationAwait behavior
    // uml: enter / { StartCarbonationLedSequance(carbonationLevel); }
    {
        // Step 1: execute action `StartCarbonationLedSequance(carbonationLevel);`
        StartCarbonationLedSequance(carbonationLevel);
    } // end of behavior for State_FilteringCarbonationAwait
}

static void STATE_FILTERINGCARBONATIONAWAIT_exit(SMSodaStreamPure* sm)
{
    // State_FilteringCarbonationAwait behavior
    // uml: exit / { StopUVLed(); }
    {
        // Step 1: execute action `StopUVLed();`
        StopUVLed();
    } // end of behavior for State_FilteringCarbonationAwait
    
    sm->state_id = SMSodaStreamPure_StateId_STATE_NORMALOPERATION;
}

static void STATE_FILTERINGCARBONATIONAWAIT_event_anykeypress(SMSodaStreamPure* sm)
{
    // State_FilteringCarbonationAwait behavior
    // uml: Event_AnyKeyPress TransitionTo(State_ExitFilteringOnly)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_FILTERINGCARBONATIONAWAIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_ExitFilteringOnly`.
        STATE_EXITFILTERINGONLY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_FilteringCarbonationAwait
    
    // No ancestor handles this event.
}

static void STATE_FILTERINGCARBONATIONAWAIT_event_bottlefullsensor(SMSodaStreamPure* sm)
{
    // State_FilteringCarbonationAwait behavior
    // uml: Event_BottleFullSensor TransitionTo(Sate_Carbonating)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_FILTERINGCARBONATIONAWAIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Sate_Carbonating`.
        SATE_CARBONATING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_FilteringCarbonationAwait
    
    // No ancestor handles this event.
}

static void STATE_FILTERINGCARBONATIONAWAIT_event_waterpumpingtimertimeout(SMSodaStreamPure* sm)
{
    // State_FilteringCarbonationAwait behavior
    // uml: Event_WaterPumpingTimerTimeout TransitionTo(State_ExitFilteringOnly)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_FILTERINGCARBONATIONAWAIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_ExitFilteringOnly`.
        STATE_EXITFILTERINGONLY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_FilteringCarbonationAwait
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_POWERON
////////////////////////////////////////////////////////////////////////////////

static void STATE_POWERON_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_POWERON;
}

static void STATE_POWERON_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_NORMALOPERATION;
}

static void STATE_POWERON_event_carbonationlevelpressed(SMSodaStreamPure* sm)
{
    // State_PowerOn behavior
    // uml: Event_CarbonationLevelPressed TransitionTo(Sate_InitCarbonatingOnly)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SMSodaStreamPure_StateId_STATE_NORMALOPERATION);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Sate_InitCarbonatingOnly`.
        SATE_INITCARBONATINGONLY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_PowerOn
    
    // No ancestor handles this event.
}

static void STATE_POWERON_event_longpresswaterfilter(SMSodaStreamPure* sm)
{
    // State_PowerOn behavior
    // uml: Event_LongPressWaterFilter TransitionTo(State_Rinsing)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SMSodaStreamPure_StateId_STATE_NORMALOPERATION);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Rinsing`.
        STATE_RINSING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_PowerOn
    
    // No ancestor handles this event.
}

static void STATE_POWERON_event_shortpresswaterfilter(SMSodaStreamPure* sm)
{
    // State_PowerOn behavior
    // uml: Event_ShortPressWaterFilter TransitionTo(State_Filtering)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SMSodaStreamPure_StateId_STATE_NORMALOPERATION);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Filtering`.
        STATE_FILTERING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_PowerOn
    
    // No ancestor handles this event.
}

static void State_PowerOn_ChoicePoint__transition(SMSodaStreamPure* sm)
{
    // State_PowerOn.<ChoicePoint>() behavior
    // uml: [IsFirstPowerON() || FilterLifeTimeExpired()] TransitionTo(State_ReadyRinseRequired)
    if (IsFirstPowerON() || FilterLifeTimeExpired())
    {
        // Step 1: Exit states until we reach `State_PowerOn` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_ReadyRinseRequired`.
        STATE_READYRINSEREQUIRED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_PowerOn.<ChoicePoint>()
    
    // State_PowerOn.<ChoicePoint>() behavior
    // uml: else TransitionTo(State_Ready)
    {
        // Step 1: Exit states until we reach `State_PowerOn` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Ready`.
        STATE_READY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_PowerOn.<ChoicePoint>()
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_POWERONINIT
////////////////////////////////////////////////////////////////////////////////

static void STATE_POWERONINIT_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_POWERONINIT;
    
    // State_PowerOnInit behavior
    // uml: enter / { LedsOff(LEDS_all); }
    {
        // Step 1: execute action `LedsOff(LEDS_all);`
        LedsOff(LEDS_all);
    } // end of behavior for State_PowerOnInit
    
    // State_PowerOnInit behavior
    // uml: enter / { AmbiantLightOff(); }
    {
        // Step 1: execute action `AmbiantLightOff();`
        AmbiantLightOff();
    } // end of behavior for State_PowerOnInit
}

static void STATE_POWERONINIT_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_POWERON;
}

static void STATE_POWERONINIT_do(SMSodaStreamPure* sm)
{
    // State_PowerOnInit behavior
    // uml: do TransitionTo(State_PowerOn.<ChoicePoint>())
    {
        // Step 1: Exit states until we reach `State_PowerOn` state (Least Common Ancestor for transition).
        STATE_POWERONINIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_PowerOn.<ChoicePoint>()`.
        // State_PowerOn.<ChoicePoint>() is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        State_PowerOn_ChoicePoint__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for State_PowerOnInit
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_READY
////////////////////////////////////////////////////////////////////////////////

static void STATE_READY_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_READY;
    
    // State_Ready behavior
    // uml: enter / { FadeInLeds(LEDS_all); }
    {
        // Step 1: execute action `FadeInLeds(LEDS_all);`
        FadeInLeds(LEDS_all);
    } // end of behavior for State_Ready
    
    // State_Ready behavior
    // uml: enter / { StartReadyTimer(); }
    {
        // Step 1: execute action `StartReadyTimer();`
        StartReadyTimer();
    } // end of behavior for State_Ready
}

static void STATE_READY_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_POWERON;
}

static void STATE_READY_event_readytimout(SMSodaStreamPure* sm)
{
    // State_Ready behavior
    // uml: Event_ReadyTimout TransitionTo(State_StandBy)
    {
        // Step 1: Exit states until we reach `State_PowerOn` state (Least Common Ancestor for transition).
        STATE_READY_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_StandBy`.
        STATE_STANDBY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_Ready
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_READYRINSEREQUIRED
////////////////////////////////////////////////////////////////////////////////

static void STATE_READYRINSEREQUIRED_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_READYRINSEREQUIRED;
    
    // State_ReadyRinseRequired behavior
    // uml: enter / { FadeInLeds(LEDS_OrangeWater); }
    {
        // Step 1: execute action `FadeInLeds(LEDS_OrangeWater);`
        FadeInLeds(LEDS_OrangeWater);
    } // end of behavior for State_ReadyRinseRequired
    
    // State_ReadyRinseRequired behavior
    // uml: enter / { StartReadyTimer(); }
    {
        // Step 1: execute action `StartReadyTimer();`
        StartReadyTimer();
    } // end of behavior for State_ReadyRinseRequired
}

static void STATE_READYRINSEREQUIRED_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_POWERON;
}

static void STATE_READYRINSEREQUIRED_event_readytimout(SMSodaStreamPure* sm)
{
    // State_ReadyRinseRequired behavior
    // uml: Event_ReadyTimout TransitionTo(State_StandBy)
    {
        // Step 1: Exit states until we reach `State_PowerOn` state (Least Common Ancestor for transition).
        STATE_READYRINSEREQUIRED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_StandBy`.
        STATE_STANDBY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_ReadyRinseRequired
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_STANDBY
////////////////////////////////////////////////////////////////////////////////

static void STATE_STANDBY_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_STANDBY;
    
    // State_StandBy behavior
    // uml: enter / { FadeOutLeds(LEDS_all); }
    {
        // Step 1: execute action `FadeOutLeds(LEDS_all);`
        FadeOutLeds(LEDS_all);
    } // end of behavior for State_StandBy
}

static void STATE_STANDBY_exit(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_POWERON;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_RINSING
////////////////////////////////////////////////////////////////////////////////

static void STATE_RINSING_enter(SMSodaStreamPure* sm)
{
    sm->state_id = SMSodaStreamPure_StateId_STATE_RINSING;
    
    // State_Rinsing behavior
    // uml: enter / { FadeOutLeds(LEDS_AllCarbonation); }
    {
        // Step 1: execute action `FadeOutLeds(LEDS_AllCarbonation);`
        FadeOutLeds(LEDS_AllCarbonation);
    } // end of behavior for State_Rinsing
    
    // State_Rinsing behavior
    // uml: enter / { StartRinsingLedSequence(); }
    {
        // Step 1: execute action `StartRinsingLedSequence();`
        StartRinsingLedSequence();
    } // end of behavior for State_Rinsing
    
    // State_Rinsing behavior
    // uml: enter / { StartWaterPump(); }
    {
        // Step 1: execute action `StartWaterPump();`
        StartWaterPump();
    } // end of behavior for State_Rinsing
    
    // State_Rinsing behavior
    // uml: enter / { ResetFilterLifetimeTimer(); }
    {
        // Step 1: execute action `ResetFilterLifetimeTimer();`
        ResetFilterLifetimeTimer();
    } // end of behavior for State_Rinsing
    
    // State_Rinsing behavior
    // uml: enter / { StartWaterPumpingTimer(); }
    {
        // Step 1: execute action `StartWaterPumpingTimer();`
        StartWaterPumpingTimer();
    } // end of behavior for State_Rinsing
    
    // State_Rinsing behavior
    // uml: enter / { StartUVLEd(); }
    {
        // Step 1: execute action `StartUVLEd();`
        StartUVLEd();
    } // end of behavior for State_Rinsing
}

static void STATE_RINSING_exit(SMSodaStreamPure* sm)
{
    // State_Rinsing behavior
    // uml: exit / { StopWaterPump(); }
    {
        // Step 1: execute action `StopWaterPump();`
        StopWaterPump();
    } // end of behavior for State_Rinsing
    
    // State_Rinsing behavior
    // uml: exit / { StopRinsingLedSequence(); }
    {
        // Step 1: execute action `StopRinsingLedSequence();`
        StopRinsingLedSequence();
    } // end of behavior for State_Rinsing
    
    // State_Rinsing behavior
    // uml: exit / { WaterLedOrangeToBlue(); }
    {
        // Step 1: execute action `WaterLedOrangeToBlue();`
        WaterLedOrangeToBlue();
    } // end of behavior for State_Rinsing
    
    // State_Rinsing behavior
    // uml: exit / { StopUVLed(); }
    {
        // Step 1: execute action `StopUVLed();`
        StopUVLed();
    } // end of behavior for State_Rinsing
    
    sm->state_id = SMSodaStreamPure_StateId_STATE_NORMALOPERATION;
}

static void STATE_RINSING_event_anykeypress(SMSodaStreamPure* sm)
{
    // State_Rinsing behavior
    // uml: Event_AnyKeyPress TransitionTo(State_Ready)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_RINSING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Ready`.
        STATE_POWERON_enter(sm);
        STATE_READY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_Rinsing
    
    // No ancestor handles this event.
}

static void STATE_RINSING_event_bottlefullsensor(SMSodaStreamPure* sm)
{
    // State_Rinsing behavior
    // uml: Event_BottleFullSensor TransitionTo(State_Ready)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_RINSING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Ready`.
        STATE_POWERON_enter(sm);
        STATE_READY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_Rinsing
    
    // No ancestor handles this event.
}

static void STATE_RINSING_event_waterpumpingtimeout(SMSodaStreamPure* sm)
{
    // State_Rinsing behavior
    // uml: Event_WaterPumpingTimeout TransitionTo(State_Ready)
    {
        // Step 1: Exit states until we reach `State_NormalOperation` state (Least Common Ancestor for transition).
        STATE_RINSING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `State_Ready`.
        STATE_POWERON_enter(sm);
        STATE_READY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for State_Rinsing
    
    // No ancestor handles this event.
}

// Thread safe.
char const * SMSodaStreamPure_state_id_to_string(SMSodaStreamPure_StateId id)
{
    switch (id)
    {
        case SMSodaStreamPure_StateId_ROOT: return "ROOT";
        case SMSodaStreamPure_StateId_SATE_HWWATCHDOG: return "SATE_HWWATCHDOG";
        case SMSodaStreamPure_StateId_SATE_SAFETYFAIL: return "SATE_SAFETYFAIL";
        case SMSodaStreamPure_StateId_SATE_TILTED: return "SATE_TILTED";
        case SMSodaStreamPure_StateId_STATE_NORMALOPERATION: return "STATE_NORMALOPERATION";
        case SMSodaStreamPure_StateId_SATE_CARBONATING: return "SATE_CARBONATING";
        case SMSodaStreamPure_StateId_SATE_INITCARBONATINGONLY: return "SATE_INITCARBONATINGONLY";
        case SMSodaStreamPure_StateId_STATE_EXITFILTERINGONLY: return "STATE_EXITFILTERINGONLY";
        case SMSodaStreamPure_StateId_STATE_FILTERING: return "STATE_FILTERING";
        case SMSodaStreamPure_StateId_STATE_FILTERINGCARBONATIONAWAIT: return "STATE_FILTERINGCARBONATIONAWAIT";
        case SMSodaStreamPure_StateId_STATE_POWERON: return "STATE_POWERON";
        case SMSodaStreamPure_StateId_STATE_POWERONINIT: return "STATE_POWERONINIT";
        case SMSodaStreamPure_StateId_STATE_READY: return "STATE_READY";
        case SMSodaStreamPure_StateId_STATE_READYRINSEREQUIRED: return "STATE_READYRINSEREQUIRED";
        case SMSodaStreamPure_StateId_STATE_STANDBY: return "STATE_STANDBY";
        case SMSodaStreamPure_StateId_STATE_RINSING: return "STATE_RINSING";
        default: return "?";
    }
}

// Thread safe.
char const * SMSodaStreamPure_event_id_to_string(SMSodaStreamPure_EventId id)
{
    switch (id)
    {
        case SMSodaStreamPure_EventId_DO: return "DO";
        case SMSodaStreamPure_EventId_EVENT_ANYKEYPRESS: return "EVENT_ANYKEYPRESS";
        case SMSodaStreamPure_EventId_EVENT_BOTTLEFULLSENSOR: return "EVENT_BOTTLEFULLSENSOR";
        case SMSodaStreamPure_EventId_EVENT_CARBONATIONDONE: return "EVENT_CARBONATIONDONE";
        case SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED: return "EVENT_CARBONATIONLEVELPRESSED";
        case SMSodaStreamPure_EventId_EVENT_HWWATCHDOG: return "EVENT_HWWATCHDOG";
        case SMSodaStreamPure_EventId_EVENT_LONGPRESSWATERFILTER: return "EVENT_LONGPRESSWATERFILTER";
        case SMSodaStreamPure_EventId_EVENT_NOTTILTED: return "EVENT_NOTTILTED";
        case SMSodaStreamPure_EventId_EVENT_READYTIMOUT: return "EVENT_READYTIMOUT";
        case SMSodaStreamPure_EventId_EVENT_SAFETYFAIL: return "EVENT_SAFETYFAIL";
        case SMSodaStreamPure_EventId_EVENT_SHORTPRESSWATERFILTER: return "EVENT_SHORTPRESSWATERFILTER";
        case SMSodaStreamPure_EventId_EVENT_TILTDETECTED: return "EVENT_TILTDETECTED";
        case SMSodaStreamPure_EventId_EVENT_WATERFILTERPRESSED: return "EVENT_WATERFILTERPRESSED";
        case SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMEOUT: return "EVENT_WATERPUMPINGTIMEOUT";
        case SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMERTIMEOUT: return "EVENT_WATERPUMPINGTIMERTIMEOUT";
        default: return "?";
    }
}
