// Autogenerated with StateSmith 0.18.0+34a94a5de0bf3f5f53012c58cebeef3eea5dac04. Last run: 2026-01-13 09:06:49 PM.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// DO NOT EDIT THIS FILE: Automatically generated by StateSmith

#ifndef SMSODASTREAMPURE_H
#define SMSODASTREAMPURE_H
#include <stdint.h>
#include <stdint.h> // for count var
#include "SMinterface.h"
#include "RTC.h" // for filter timers methods


typedef enum SMSodaStreamPure_EventId
{
    SMSodaStreamPure_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    SMSodaStreamPure_EventId_EVENT_ANYKEYPRESS = 1,
    SMSodaStreamPure_EventId_EVENT_BOTTLEFULLSENSOR = 2,
    SMSodaStreamPure_EventId_EVENT_CARBLEVELLONGPRESSED = 3,
    SMSodaStreamPure_EventId_EVENT_CARBLEVELSHORTPRESSED = 4,
    SMSodaStreamPure_EventId_EVENT_ENTER_GUI_CONTROLLED_MODE = 5,
    SMSodaStreamPure_EventId_EVENT_EXIT_GUI_CONTROLLED_MODE = 6,
    SMSodaStreamPure_EventId_EVENT_FILTERBUTTONLONGPRESSED = 7,
    SMSodaStreamPure_EventId_EVENT_FILTERBUTTONSHORTPRESSED = 8,
    SMSodaStreamPure_EventId_EVENT_HWWATCHDOG = 9,
    SMSodaStreamPure_EventId_EVENT_PRIMARYBUTTONPRESSED = 10,
    SMSodaStreamPure_EventId_EVENT_SAFETYFAIL = 11
} SMSodaStreamPure_EventId;

enum
{
    SMSodaStreamPure_EventIdCount = 12
};

typedef enum SMSodaStreamPure_StateId
{
    SMSodaStreamPure_StateId_ROOT = 0,
    SMSodaStreamPure_StateId_STATE_AUTOMATICMODE = 1,
    SMSodaStreamPure_StateId_STATE_AWAKE = 2,
    SMSodaStreamPure_StateId_STATE_READY = 3,
    SMSodaStreamPure_StateId_STATE_SHOWFILTERSTATUS = 4,
    SMSodaStreamPure_StateId_STATE_SPLASH = 5,
    SMSodaStreamPure_StateId_STATE_UVSTATUS = 6,
    SMSodaStreamPure_StateId_STATE_CARBONATING = 7,
    SMSodaStreamPure_StateId_STATE_CARBLEDS = 8,
    SMSodaStreamPure_StateId_STATE_CARBONATING_OFF = 9,
    SMSodaStreamPure_StateId_STATE_CARBONATING_ON = 10,
    SMSodaStreamPure_StateId_STATE_FILTERTOCARBDELAY = 11,
    SMSodaStreamPure_StateId_STATE_START_CARBONATING = 12,
    SMSodaStreamPure_StateId_STATE_EXIT_CARBONATING = 13,
    SMSodaStreamPure_StateId_STATE_EXITFILTERINGONLY = 14,
    SMSodaStreamPure_StateId_STATE_FILTERING = 15,
    SMSodaStreamPure_StateId_STATE_FILTERINGNOWATERWARNING = 16,
    SMSodaStreamPure_StateId_STATE_MAKEDRINKDONE = 17,
    SMSodaStreamPure_StateId_STATE_NEXTFILLPENDING = 18,
    SMSodaStreamPure_StateId_STATE_POWERONCHECKOOTBPRESS = 19,
    SMSodaStreamPure_StateId_STATE_PRECHECKWATERSENSOR = 20,
    SMSodaStreamPure_StateId_STATE_RESETCO2COUNTER = 21,
    SMSodaStreamPure_StateId_STATE_RESETFILTERWARNING = 22,
    SMSodaStreamPure_StateId_STATE_RESETRINSINGTIMER = 23,
    SMSodaStreamPure_StateId_STATE_RESETTOOOTB = 24,
    SMSodaStreamPure_StateId_STATE_RINSING = 25,
    SMSodaStreamPure_StateId_STATE_RINSINGDONEOK = 26,
    SMSodaStreamPure_StateId_STATE_RINSINGENDLEDS = 27,
    SMSodaStreamPure_StateId_STATE_RINSINGNOWATERWARNING = 28,
    SMSodaStreamPure_StateId_STATE_RINSINGPRECHECKWATERSENSOR = 29,
    SMSodaStreamPure_StateId_STATE_RINSINGSTART = 30,
    SMSodaStreamPure_StateId_STATE_SETLEVEL = 31,
    SMSodaStreamPure_StateId_STATE_SHOWSTATUS = 32,
    SMSodaStreamPure_StateId_STATE_SLEEPING = 33,
    SMSodaStreamPure_StateId_STATE_SOLENOID_OFF = 34,
    SMSodaStreamPure_StateId_STATE_GUICONTROLMODE = 35,
    SMSodaStreamPure_StateId_STATE_GUIMODEWAITCOMMANDS = 36,
    SMSodaStreamPure_StateId_STATE_STOPWATERPUMP = 37,
    SMSodaStreamPure_StateId_STATE_HWWATCHDOG = 38,
    SMSodaStreamPure_StateId_STATE_SAFETYFAIL = 39,
    SMSodaStreamPure_StateId_STATE_TILTED = 40
} SMSodaStreamPure_StateId;

enum
{
    SMSodaStreamPure_StateIdCount = 41
};


// Generated state machine
// forward declaration
typedef struct SMSodaStreamPure SMSodaStreamPure;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct SMSodaStreamPure_Vars
{
    uint16_t count; // this var can be referenced in diagram
    bool pumpStopsOnSensor;
    uint16_t carbCycle;
} SMSodaStreamPure_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void SMSodaStreamPure_ctor(SMSodaStreamPure* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void SMSodaStreamPure_start(SMSodaStreamPure* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void SMSodaStreamPure_dispatch_event(SMSodaStreamPure* sm, SMSodaStreamPure_EventId event_id);

// Generated state machine
struct SMSodaStreamPure
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    SMSodaStreamPure_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    SMSodaStreamPure_Vars vars;
};

#endif // SMSODASTREAMPURE_H
