// Autogenerated with StateSmith 0.17.2+a7141c241054b3177bab267557ecb45a8dcedd67.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var
#include "SMinterface.h"


typedef enum SMSodaStreamPure_EventId
{
    SMSodaStreamPure_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    SMSodaStreamPure_EventId_EVENT_ANYKEYPRESS = 1,
    SMSodaStreamPure_EventId_EVENT_BOTTLEFULLSENSOR = 2,
    SMSodaStreamPure_EventId_EVENT_CARBOFF = 3,
    SMSodaStreamPure_EventId_EVENT_CARBON = 4,
    SMSodaStreamPure_EventId_EVENT_CARBONATIONDONE = 5,
    SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED = 6,
    SMSodaStreamPure_EventId_EVENT_ENTER_GUI_CONTROLLED_MODE = 7,
    SMSodaStreamPure_EventId_EVENT_EXIT_GUI_CONTROLLED_MODE = 8,
    SMSodaStreamPure_EventId_EVENT_HWWATCHDOG = 9,
    SMSodaStreamPure_EventId_EVENT_LONGPRESSWATERFILTER = 10,
    SMSodaStreamPure_EventId_EVENT_NOTTILTED = 11,
    SMSodaStreamPure_EventId_EVENT_READYTIMOUT = 12,
    SMSodaStreamPure_EventId_EVENT_SAFETYFAIL = 13,
    SMSodaStreamPure_EventId_EVENT_SETLED = 14,
    SMSodaStreamPure_EventId_EVENT_SETRGBLED = 15,
    SMSodaStreamPure_EventId_EVENT_SHORTPRESSWATERFILTER = 16,
    SMSodaStreamPure_EventId_EVENT_SOLENDOIDPUMPPOWEROFF = 17,
    SMSodaStreamPure_EventId_EVENT_SOLENDOIDPUMPPOWERON = 18,
    SMSodaStreamPure_EventId_EVENT_STARTSTATUSTRANSMIT = 19,
    SMSodaStreamPure_EventId_EVENT_STOP = 20,
    SMSodaStreamPure_EventId_EVENT_STOPSTATUSTRANSMIT = 21,
    SMSodaStreamPure_EventId_EVENT_TILTDETECTED = 22,
    SMSodaStreamPure_EventId_EVENT_UVLEDOFF = 23,
    SMSodaStreamPure_EventId_EVENT_UVLEDON = 24,
    SMSodaStreamPure_EventId_EVENT_WAREPUMPON = 25,
    SMSodaStreamPure_EventId_EVENT_WATERFILTERPRESSED = 26,
    SMSodaStreamPure_EventId_EVENT_WATERPUMOONNOSENSOR = 27,
    SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMEOUT = 28,
    SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMERTIMEOUT = 29,
    SMSodaStreamPure_EventId_EVENT_WATERPUMPOFF = 30
} SMSodaStreamPure_EventId;

enum
{
    SMSodaStreamPure_EventIdCount = 31
};

typedef enum SMSodaStreamPure_StateId
{
    SMSodaStreamPure_StateId_ROOT = 0,
    SMSodaStreamPure_StateId_SATE_HWWATCHDOG = 1,
    SMSodaStreamPure_StateId_SATE_SAFETYFAIL = 2,
    SMSodaStreamPure_StateId_SATE_TILTED = 3,
    SMSodaStreamPure_StateId_STAT_GUICONTROLMODE = 4,
    SMSodaStreamPure_StateId_STATE_CARBOFF = 5,
    SMSodaStreamPure_StateId_STATE_CARBON = 6,
    SMSodaStreamPure_StateId_STATE_GUIMODEWAITCOMMANDS = 7,
    SMSodaStreamPure_StateId_STATE_INITGUIMODE = 8,
    SMSodaStreamPure_StateId_STATE_RGBLEDON = 9,
    SMSodaStreamPure_StateId_STATE_SETLED = 10,
    SMSodaStreamPure_StateId_STATE_SOLENOIDPUMPPOWEROFF = 11,
    SMSodaStreamPure_StateId_STATE_SOLENOIDPUMPPOWERON = 12,
    SMSodaStreamPure_StateId_STATE_STARTSTATUSTRANSMIT = 13,
    SMSodaStreamPure_StateId_STATE_STOP = 14,
    SMSodaStreamPure_StateId_STATE_STOPSTATUSTRANSMIT = 15,
    SMSodaStreamPure_StateId_STATE_UVLEDOFF = 16,
    SMSodaStreamPure_StateId_STATE_UVLEDON = 17,
    SMSodaStreamPure_StateId_STATE_WATERPUMPOFF = 18,
    SMSodaStreamPure_StateId_STATE_WATERPUMPON = 19,
    SMSodaStreamPure_StateId_STATE_WATERPUMPONNOSENSOR = 20,
    SMSodaStreamPure_StateId_STATE_AUTOMATICMODE = 21,
    SMSodaStreamPure_StateId_SATE_CARBONATING = 22,
    SMSodaStreamPure_StateId_SATE_INITCARBONATINGONLY = 23,
    SMSodaStreamPure_StateId_STATE_EXITFILTERINGONLY = 24,
    SMSodaStreamPure_StateId_STATE_FILTERING = 25,
    SMSodaStreamPure_StateId_STATE_FILTERINGCARBONATIONAWAIT = 26,
    SMSodaStreamPure_StateId_STATE_POWERON = 27,
    SMSodaStreamPure_StateId_STATE_POWERONINIT = 28,
    SMSodaStreamPure_StateId_STATE_READY = 29,
    SMSodaStreamPure_StateId_STATE_READYRINSEREQUIRED = 30,
    SMSodaStreamPure_StateId_STATE_STANDBY = 31,
    SMSodaStreamPure_StateId_STATE_RINSING = 32
} SMSodaStreamPure_StateId;

enum
{
    SMSodaStreamPure_StateIdCount = 33
};


// Generated state machine
// forward declaration
typedef struct SMSodaStreamPure SMSodaStreamPure;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct SMSodaStreamPure_Vars
{
    uint16_t count; // this var can be referenced in diagram
} SMSodaStreamPure_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void SMSodaStreamPure_ctor(SMSodaStreamPure* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void SMSodaStreamPure_start(SMSodaStreamPure* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void SMSodaStreamPure_dispatch_event(SMSodaStreamPure* sm, SMSodaStreamPure_EventId event_id);

// Thread safe.
char const * SMSodaStreamPure_state_id_to_string(SMSodaStreamPure_StateId id);

// Thread safe.
char const * SMSodaStreamPure_event_id_to_string(SMSodaStreamPure_EventId id);

// Generated state machine
struct SMSodaStreamPure
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    SMSodaStreamPure_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    SMSodaStreamPure_Vars vars;
};

