// Autogenerated with StateSmith 0.17.2+a7141c241054b3177bab267557ecb45a8dcedd67.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var
#include "SMinterface.h"


typedef enum SMSodaStreamPure_EventId
{
    SMSodaStreamPure_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    SMSodaStreamPure_EventId_EVENT_ANYKEYPRESS = 1,
    SMSodaStreamPure_EventId_EVENT_BOTTLEFULLSENSOR = 2,
    SMSodaStreamPure_EventId_EVENT_CARBONATIONDONE = 3,
    SMSodaStreamPure_EventId_EVENT_CARBONATIONLEVELPRESSED = 4,
    SMSodaStreamPure_EventId_EVENT_HWWATCHDOG = 5,
    SMSodaStreamPure_EventId_EVENT_LONGPRESSWATERFILTER = 6,
    SMSodaStreamPure_EventId_EVENT_NOTTILTED = 7,
    SMSodaStreamPure_EventId_EVENT_READYTIMOUT = 8,
    SMSodaStreamPure_EventId_EVENT_SAFETYFAIL = 9,
    SMSodaStreamPure_EventId_EVENT_SHORTPRESSWATERFILTER = 10,
    SMSodaStreamPure_EventId_EVENT_TILTDETECTED = 11,
    SMSodaStreamPure_EventId_EVENT_WATERFILTERPRESSED = 12,
    SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMEOUT = 13,
    SMSodaStreamPure_EventId_EVENT_WATERPUMPINGTIMERTIMEOUT = 14
} SMSodaStreamPure_EventId;

enum
{
    SMSodaStreamPure_EventIdCount = 15
};

typedef enum SMSodaStreamPure_StateId
{
    SMSodaStreamPure_StateId_ROOT = 0,
    SMSodaStreamPure_StateId_SATE_HWWATCHDOG = 1,
    SMSodaStreamPure_StateId_SATE_SAFETYFAIL = 2,
    SMSodaStreamPure_StateId_SATE_TILTED = 3,
    SMSodaStreamPure_StateId_STATE_NORMALOPERATION = 4,
    SMSodaStreamPure_StateId_SATE_CARBONATING = 5,
    SMSodaStreamPure_StateId_SATE_INITCARBONATINGONLY = 6,
    SMSodaStreamPure_StateId_STATE_EXITFILTERINGONLY = 7,
    SMSodaStreamPure_StateId_STATE_FILTERING = 8,
    SMSodaStreamPure_StateId_STATE_FILTERINGCARBONATIONAWAIT = 9,
    SMSodaStreamPure_StateId_STATE_POWERON = 10,
    SMSodaStreamPure_StateId_STATE_POWERONINIT = 11,
    SMSodaStreamPure_StateId_STATE_READY = 12,
    SMSodaStreamPure_StateId_STATE_READYRINSEREQUIRED = 13,
    SMSodaStreamPure_StateId_STATE_STANDBY = 14,
    SMSodaStreamPure_StateId_STATE_RINSING = 15
} SMSodaStreamPure_StateId;

enum
{
    SMSodaStreamPure_StateIdCount = 16
};


// Generated state machine
// forward declaration
typedef struct SMSodaStreamPure SMSodaStreamPure;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct SMSodaStreamPure_Vars
{
    uint16_t count; // this var can be referenced in diagram
} SMSodaStreamPure_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void SMSodaStreamPure_ctor(SMSodaStreamPure* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void SMSodaStreamPure_start(SMSodaStreamPure* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void SMSodaStreamPure_dispatch_event(SMSodaStreamPure* sm, SMSodaStreamPure_EventId event_id);

// Thread safe.
char const * SMSodaStreamPure_state_id_to_string(SMSodaStreamPure_StateId id);

// Thread safe.
char const * SMSodaStreamPure_event_id_to_string(SMSodaStreamPure_EventId id);

// Generated state machine
struct SMSodaStreamPure
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    SMSodaStreamPure_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    SMSodaStreamPure_Vars vars;
};

